### PR TITLE
Add a lock reason with "resolved"

### PR DESCRIPTION
**Pull request by hzoo**
Ref https://github.com/babel/babel/pull/7839#discussion_r185066696

For the preview, I looked at https://github.com/octokit/rest.js#api-previews and you can already just pass a header (thanks @gr2m)

image

> When locking an issue via the issues API, you can now provide an optional reason that will be visible to anyone who views the issue. Valid lock reasons are "off-topic", "too heated", "resolved", and "spam". Providing a lock reason can help make it clearer to contributors why an issue was locked, and what kinds of behavior may result in issues being locked in the future. 

`resolved` seems to make the most since here so I just hardcoded it. Although maybe we can suggest a new one for this use-case. Feel free to modify this PR if needed

### CODE REVIEW

**Comment by dessant** [comment]
@hzoo, looks great, the change has been deployed, thanks a lot!

**Comment by hzoo** [comment]
Awesome thanks! will try to merge https://github.com/babel/babel/pull/7839 next!

**Comment by hzoo** [comment]
Also this was an obvious answer too https://twitter.com/pshrmn/status/991093233475293184

maybe we should add an optional label in place of a comment (like `outdated`)

**Comment by hzoo** [comment]
Ok made https://github.com/dessant/lock-threads/pull/4 if that is useful

**Pull request merged**
