### PR TITLE
Update dependancy to remove const error

### PR DESCRIPTION
**Pull request by netniV**
This fixes the octokit error caused by the Toolkit GitHub action.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Looking forward to this patch. In the meantime, I wonder if it works to use `uses: netniV/lock-threads@patch-1`? My first attempt seemed to fail silently. I'm about to give it another try….

**Comment by netniV** [comment]
I would think you'd need to specify using my specific version in your workflow file. However, don't quote me on that as whilst I think you can do, not entirely sure on that as I'm still learning the mysterious art of github actions

**Comment by thinkyhead** [comment]
I used the path from above and when the job ran it gave this ("successful") result…
image

**Comment by netniV** [comment]
That’s interesting. If you turn on the debug etc. does it definitely pull in the later GitHub action sources ? They definitely fixed it in that one from what I read of the sources.

**Comment by dessant** [comment]
Hi folks! Both package.json and package-lock.json need to be updated by running `npm update @actions/github`, and then the dist package pulled by workflows needs to be built with ncc by running `npm run package`. The last step should usually be done by maintainers for security reasons, since it produces a 1 MB file with a diff that is sometimes huge. I'll update all dependencies and release a new version today.

**Comment by netniV** [comment]
I did see that the other file needs to be updated but figured that was a security thing done by yourself. Glad to have it resolved though :)

**Pull request closed without merging**
